stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
  - export PATH=$JAVA_HOME/bin:$PATH
  - mvn $MAVEN_CLI_OPTS dependency:go-offline

build_backend:
  stage: build
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - backend/target/*.jar

test_backend:
  stage: test
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS test

build_frontend:
  stage: build
  image: node:14
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build

test_frontend:
  stage: test
  image: node:14
  script:
    - cd frontend
    - npm install
    - npm test